# Memory Stress Chaos Experiment
# Tests OOM handling and memory pressure behavior
#
# Expected outcome:
# - Pod may be OOM killed if memory exceeds limits
# - Kubernetes should restart the pod
# - Other pods should not be affected
#
# Metrics to watch:
# - container_memory_usage_bytes
# - container_memory_working_set_bytes
# - kube_pod_container_status_restarts_total

apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: inference-memory-stress
  namespace: chaos-testing
  labels:
    app: chaos-testing
    experiment: memory-stress
spec:
  mode: one  # Only stress one pod to avoid cascade
  selector:
    namespaces:
      - kserve
    labelSelectors:
      component: predictor
  stressors:
    memory:
      workers: 1
      size: "256MB"  # Allocate 256MB of memory
  duration: "3m"

---
# MLflow memory stress
# Tests metadata service under memory pressure
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: mlflow-memory-stress
  namespace: chaos-testing
  labels:
    app: chaos-testing
    experiment: mlflow-memory
spec:
  mode: one
  selector:
    namespaces:
      - mlflow
    labelSelectors:
      app.kubernetes.io/name: mlflow
  stressors:
    memory:
      workers: 2
      size: "512MB"
  duration: "2m"

---
# Combined CPU and Memory stress
# Tests system under realistic high-load conditions
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: combined-resource-stress
  namespace: chaos-testing
  labels:
    app: chaos-testing
    experiment: combined-stress
spec:
  mode: all
  selector:
    namespaces:
      - kserve
    labelSelectors:
      component: predictor
  stressors:
    cpu:
      workers: 1
      load: 70
    memory:
      workers: 1
      size: "128MB"
  duration: "5m"

---
# Memory leak simulation
# Gradually increasing memory usage to test detection
apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: memory-leak-simulation
  namespace: chaos-testing
  labels:
    app: chaos-testing
    experiment: memory-leak
spec:
  mode: one
  selector:
    namespaces:
      - kserve
    labelSelectors:
      component: predictor
  stressors:
    memory:
      workers: 1
      size: "64MB"
      # Memory is allocated but not freed, simulating a leak
      options:
        - "--vm-hang"
        - "0"  # Don't free memory
  duration: "10m"